### ISSUE TITLE
Is it possible to create a custom IP or ddns play function?

### ISSUE THREAD

**Issue by Shan-Mk** [ywnico/vitaki-fork#14]
Can it support the external IP connection saving setting function like Android Chiaki?
just like this picture ip :xxxxx.dyndns.org link ps5!
![1733027691882](https://github.com/user-attachments/assets/c17817bd-eb62-4762-9daf-35c6da9188cb)

**Comment by ywnico** [comment]
This is my top priority to implement next, but I am afraid I can't give a timeline right now
