### ISSUE TITLE
[BUG] Adjust controls in Vitaki Settings not working

### ISSUE THREAD

**Issue by pokechar** [ywnico/vitaki-fork#9]
I have tried changing the control settings in the Vitaki settings but it doesn't seem to work, for example I can't get the L2 and R2 buttons to work.
You can check if there is any problem with that.
Thank you!

**Comment by ywnico** [comment]
So, you change the number in Vitaki settings and there is no effect? E.g., the back touchpad quadrants have no effect if the map number is 0? And back touchpad + R1 has no effect if the map number is 99?

**Comment by pokechar** [comment]
I tried 0 and 99 in the Vitaki settings but have no effect for the L2 and R2 buttons.
The rear touchpad quadrants have no effect if the map number is 0 and the rear touchpad + R1 has no effect if the map number is 99.

**Comment by ywnico** [comment]
Hmm...are you sure your rear touchpad works? Or do you have some plugin installed that might be intercepting it?

**Comment by pokechar** [comment]
The problem was that the touch does not work while charging.
Thanks!

**Comment by ywnico** [comment]
Oh, good to know! Glad it's working now.
